version: 2
jobs:
  build:
    docker:
      - image: blackjacktheviking/liblifthttpbuilder:0.2
      - image: nginx:stable
    steps:
      - run: 
          name: update
          command: apt-get -y update 
      - run:
          name: install dependencies
          command: |
            apt-get -y install \
              git \
              cmake \
              ninja-build \
              g++ \
              clang \
              zlib1g-dev \
              libcurl4-openssl-dev \
              libuv1-dev
      - checkout
      - run:
          name: build release g++
          command: |
            mkdir build-release-g++
            cd build-release-g++ 
            cmake \
                -GNinja \
                -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_C_COMPILER=gcc \
                -DCMAKE_CXX_COMPILER=g++ .. 
            ninja
      - run:
          name: build release clang++
          command: |
            mkdir build-release-clang++
            cd build-release-clang++ 
            cmake \
              -GNinja \
              -DCMAKE_BUILD_TYPE=Release \
              -DCMAKE_C_COMPILER=clang \
              -DCMAKE_CXX_COMPILER=clang++ .. 
            ninja
      - run:
          name: test release g++
          command: |
            cd build-release-g++
            ctest -V
      - run:
          name: test release clang++
          command: |
            cd build-release-clang++
            ctest -V
